AllCops:
  TargetRubyVersion: 3.1 # the oldest version we support (don't suggest syntax newer than that)
  # NOTE: I tried using `Enabled: false`, but that had no effect,
  # at least in my editor. This was the only way I get Rubocop
  # to stop yelling at me.
  Exclude:
    - bin/**/*
    - build/generated/**/*
    - Gemfile
    - lib/**/*
    - Rakefile
    - spec/**/*.rb
    - src/**/*
    - test/**/*
    - vendor/**/*
