FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/HeredocIndentation:
  Enabled: false

Metrics:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/AccessModifierDeclarations:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WhileUntilModifier:
  Enabled: false
