alias $FS $;
alias $FIELD_SEPARATOR $;
alias $OFS $,
alias $OUTPUT_FIELD_SEPARATOR $,
alias $RS $/
alias $INPUT_RECORD_SEPARATOR $/
alias $ORS $\
alias $OUTPUT_RECORD_SEPARATOR $\
alias $INPUT_LINE_NUMBER $.
alias $NR $.
alias $DEFAULT_OUTPUT $>
alias $DEFAULT_INPUT $<
alias $PID $$
alias $CHILD_STATUS $?
alias $PROCESS_ID $$
alias $CHILD_STATUS $?
alias $LAST_MATCH_INFO $~
alias $ARGV $*
alias $MATCH $&
alias $PREMATCH $`
alias $POSTMATCH $'
alias $LAST_PAREN_MATCH $+
